### PR TITLE
Add commit message validation

### PR DESCRIPTION
**Pull request by zeromberto**
A new setting is added to the project specific settings to enable and enter a regular expression. This regular expression is used to validate commit messages during checkin. If the commit message does not match the regular expression the commit is cancelled and the author needs to adjust the commit message.

### CODE REVIEW

**Comment by zeromberto** [comment]
Hi @zielu what do you think about this PR?

**Comment by zielu** [comment]
@zeromberto I'm reviewing :)

**Comment by zielu** [comment]
Released to EAP channel in 193.3.0

**Comment by zielu** [comment]
Released to Stable in 193.3.2

**Pull request merged**
